Alpha/Controllers/AccessoriesController.cs
using Microsoft.AspNetCore.Mvc;
using Alpha.Models;
using Microsoft.AspNetCore.SignalR;
using static System.Reflection.Metadata.BlobBuilder;
using Microsoft.AspNetCore.Mvc.Infrastructure;
namespace Alpha.Controllers
{
    public class AccessoriesController : Controller
    {
        private readonly ILogger<AccessoriesController> _logger;
        private readonly IWebHostEnvironment _env;
        private readonly IRepository<Accessories> _repository = new GenericRepos<Accessories>();
        public AccessoriesController(ILogger<AccessoriesController> logger, IWebHostEnvironment env)
        {

            _logger = logger;
            _env = env;

        }
        public IActionResult Index()
        {
            var l = _repository.GetAll();
            return View(l);
        }

        [HttpPost]
        public IActionResult Add([FromForm] Accessories b)
        {
            string wwwrootPath = _env.WebRootPath;
            string path = Path.Combine(wwwrootPath, "UploadedFiles/Accessories");

            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            string filePath = Path.Combine(path, b.CoverImage.FileName);
            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                b.CoverImage.CopyTo(fileStream);
            }

            string imagePathinroot = "~/UploadedFiles/Accessories/" + b.CoverImage.FileName;
            b.ImageUrl = imagePathinroot;

            
            ModelState.Clear(); 
            TryValidateModel(b); 

            if (!ModelState.IsValid)
            {
              
                foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                {
                    _logger.LogError("Validation Error: " + error.ErrorMessage);
                }

                return View(b);
            }
            _repository.Add(b);
            return RedirectToAction("Index"); 
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Delete()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Delete(string clothe)
        {
            if (string.IsNullOrEmpty(clothe))
            {
                return BadRequest();
            }
            var existing = _repository.GetAll().FirstOrDefault(x => x.AccessoriesName == clothe);

            if (existing == null)
            {
                return NotFound($"Accessories Outfit with name '{clothe}' not found.");
            }

            _repository.Delete(existing.Id);
            return View();
        }

    }
}

Alpha/Controllers/MenController.cs
using Microsoft.AspNetCore.Mvc;
using Alpha.Models;
using Microsoft.AspNetCore.SignalR;
using static System.Reflection.Metadata.BlobBuilder;
using Microsoft.AspNetCore.Mvc.Infrastructure;
namespace Alpha.Controllers
{
    public class MenController : Controller
    {
        private readonly ILogger<MenController> _logger;
        private readonly IWebHostEnvironment _env;
        private readonly IRepository<Men> _repository = new GenericRepos<Men>();
        public MenController(ILogger<MenController> logger, IWebHostEnvironment env)
        {

            _logger = logger;
            _env = env;

        }
        public IActionResult Index()
        {
            var l = _repository.GetAll();
            return View(l);
        }

        [HttpPost]
        public IActionResult Add([FromForm] Men b)
        {
            string wwwrootPath = _env.WebRootPath;
            string path = Path.Combine(wwwrootPath, "UploadedFiles/Men");

            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            string filePath = Path.Combine(path, b.CoverImage.FileName);
            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                b.CoverImage.CopyTo(fileStream);
            }

            string imagePathinroot = "~/UploadedFiles/Men/" + b.CoverImage.FileName;
            b.ImageUrl = imagePathinroot;

           
            ModelState.Clear(); 
            TryValidateModel(b); 

            if (!ModelState.IsValid)
            {
                foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                {
                    _logger.LogError("Validation Error: " + error.ErrorMessage);
                }

                return View(b);
            }
            _repository.Add(b);
            return RedirectToAction("Index"); 
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Delete()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Delete(string clothe)
        {
            if (string.IsNullOrEmpty(clothe))
            {
                return BadRequest();
            }
            var existing = _repository.GetAll().FirstOrDefault(x => x.MenOutfitName == clothe);

            if (existing == null)
            {
                return NotFound($"Men Outfit with name '{clothe}' not found.");
            }

            _repository.Delete(existing.Id);
            return View();
        }

    }
}

Alpha/Controllers/SkinCareController.cs
using Microsoft.AspNetCore.Mvc;
using Alpha.Models;
using Microsoft.AspNetCore.SignalR;
using static System.Reflection.Metadata.BlobBuilder;
using Microsoft.AspNetCore.Mvc.Infrastructure;
namespace Alpha.Controllers
{
    public class SkinCareController : Controller
    {
        private readonly ILogger<SkinCareController> _logger;
        private readonly IWebHostEnvironment _env;
        private readonly IRepository<SkinCare> _repository = new GenericRepos<SkinCare>();
        public SkinCareController(ILogger<SkinCareController> logger, IWebHostEnvironment env)
        {

            _logger = logger;
            _env = env;

        }
        public IActionResult Index()
        {
            var l = _repository.GetAll();
            return View(l);
        }

        [HttpPost]
        public IActionResult Add([FromForm] SkinCare b)
        {
            string wwwrootPath = _env.WebRootPath;
            string path = Path.Combine(wwwrootPath, "UploadedFiles/SkinCare");

            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            string filePath = Path.Combine(path, b.CoverImage.FileName);
            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                b.CoverImage.CopyTo(fileStream);
            }

            string imagePathinroot = "~/UploadedFiles/SkinCare/" + b.CoverImage.FileName;
            b.ImageUrl = imagePathinroot;

           
            ModelState.Clear(); 
            TryValidateModel(b);

            if (!ModelState.IsValid)
            {
               
                foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                {
                    _logger.LogError("Validation Error: " + error.ErrorMessage);
                }

                return View(b); 
            }
            _repository.Add(b);
            return RedirectToAction("Index"); 
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Delete()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Delete(string clothe)
        {
            if (string.IsNullOrEmpty(clothe))
            {
                return BadRequest();
            }
            var existing = _repository.GetAll().FirstOrDefault(x => x.SkinCareName == clothe);

            if (existing == null)
            {
                return NotFound($"SkinCare Outfit with name '{clothe}' not found.");
            }

            _repository.Delete(existing.Id);
            return View();
        }

    }
}

Alpha/Controllers/WomenController.cs
using Microsoft.AspNetCore.Mvc;
using Alpha.Models;
using Microsoft.AspNetCore.SignalR;
using static System.Reflection.Metadata.BlobBuilder;
using Microsoft.AspNetCore.Mvc.Infrastructure;
namespace Alpha.Controllers
{
    public class WomenController : Controller
    {
        private readonly ILogger<WomenController> _logger;
        private readonly IWebHostEnvironment _env;
        private readonly IRepository<Women> _repository = new GenericRepos<Women>();
        public WomenController(ILogger<WomenController> logger, IWebHostEnvironment env)
        {

            _logger = logger;
            _env = env;

        }
        public IActionResult Index()
        {
            var l = _repository.GetAll();
            return View(l);
        }

        [HttpPost]
        public IActionResult Add([FromForm] Women b)
        {
            string wwwrootPath = _env.WebRootPath;
            string path = Path.Combine(wwwrootPath, "UploadedFiles/Women");

            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            string filePath = Path.Combine(path, b.CoverImage.FileName);
            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                b.CoverImage.CopyTo(fileStream);
            }

            string imagePathinroot = "~/UploadedFiles/Women/" + b.CoverImage.FileName;
            b.ImageUrl = imagePathinroot;

           
            ModelState.Clear(); 
            TryValidateModel(b);
            if (!ModelState.IsValid)
            {
                foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                {
                    _logger.LogError("Validation Error: " + error.ErrorMessage);
                }

                return View(b);
            }
            _repository.Add(b);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Delete()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Delete(string clothe)
        {
            if (string.IsNullOrEmpty(clothe))
            {
                return BadRequest();
            }
            var existing = _repository.GetAll().FirstOrDefault(x=>x.WomenOutfitName == clothe);
           
            if (existing == null)
            {
                return NotFound($"Women Outfit with name '{clothe}' not found.");
            }
            
            _repository.Delete(existing.Id);
            return View();
        }
      
    }
}

Alpha/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    @* <meta name="description" content=" ">
    <meta name="keywords" content="alpha, unica, creative, html"> *@
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Alpha</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cookie&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="~/css/bootstrap.min.css" asp-append-version="true">
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true">
    <link rel="stylesheet" href="~/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="~/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/magnific-popup.css" type="text/css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/slicknav.min.css" type="text/css">

</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Offcanvas Menu Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="offcanvas__close">+</div>
        <ul class="offcanvas__widget">
            <li><span class="icon_search search-switch"></span></li>
            <li>
                <a href="#">
                    <span class="icon_heart_alt"></span>
                    <div class="tip">2</div>
                </a>
            </li>
            <li>
                <a href="#">
                    <span class="icon_bag_alt"></span>
                    <div class="tip">2</div>
                </a>
            </li>
        </ul>
        <div class="offcanvas__logo">
            <a asp-controller="Home" asp-action="Index"><img src="~/img/logo.png" alt=""></a>
        </div>
        <div id="mobile-menu-wrap"></div>
        <div class="offcanvas__auth">
            <a href="#">Login</a>
            <a href="#">Register</a>
        </div>
    </div>
    <!-- Offcanvas Menu End -->
    <!-- Header Section Begin -->
    <header class="header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-xl-3 col-lg-2">
                    <div class="header__logo">
                        <a asp-controller="Home" asp-action="Index"><img src="~/img/l.png" alt="" style="height:60px;"></a>
                    </div>
                </div>
                <div class="col-xl-6 col-lg-7 p-3">
                    <nav class="header__menu">
                        <ul>
                            <li class="active"><a asp-controller="Home" asp-action="Index">Home</a></li>

                            <li>
                                <a href="#">Categories</a>
                                <ul class="dropdown">

                                    <li><a asp-controller="Women" asp-action="">Women</a></li>
                                    <li><a asp-controller="Men" asp-action="Index">Men</a></li>
                                    <li><a asp-controller="SkinCare" asp-action="Index">Skin Care</a></li>
                                    <li><a asp-controller="Accessories" asp-action="Index">Accessories</a></li>
                                </ul>
                            </li>


                            <li><a asp-controller="Cart" asp-action="Index">Shop Cart</a></li>
                            <li><a asp-controller ="Cart" asp-action="CheckOut">Checkout</a></li>
                            <li><a asp-controller="Home" asp-action="About">About</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-3 p-3">
                    <div class="header__right">
                        <div class="header__right__auth">
                            <a href="/Identity/Account/Login">Login</a>
                            <a href="/Identity/Account/Register">Register</a>

                        </div>
                        <ul class="header__right__widget">
                            <li><span class="icon_search search-switch"></span></li>
                            <li>
                                <a href="#">
                                    <span class="icon_heart_alt"></span>
                                    <div class="tip">2</div>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="icon_bag_alt"></span>
                                    <div class="tip">2</div>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="canvas__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </header>
    <!-- Header Section End -->
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>




    <!-- Instagram Begin -->
    <div class="instagram mt-5">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                    <div class="instagram__item set-bg" data-setbg="/img/instagram/insta-1.jpg">
                        <div class="instagram__text">
                            <i class="fa fa-instagram"></i>
                            <a href="#">alpha</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                    <div class="instagram__item set-bg" data-setbg="/img/instagram/insta-2.jpg">
                        <div class="instagram__text">
                            <i class="fa fa-instagram"></i>

                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                    <div class="instagram__item set-bg" data-setbg="/img/instagram/insta-3.jpg">
                        <div class="instagram__text">
                            <i class="fa fa-instagram"></i>

                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                    <div class="instagram__item set-bg" data-setbg="/img/instagram/insta-4.jpg">
                        <div class="instagram__text">
                            <i class="fa fa-instagram"></i>

                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                    <div class="instagram__item set-bg" data-setbg="/img/instagram/insta-5.jpg">
                        <div class="instagram__text">
                            <i class="fa fa-instagram"></i>

                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                    <div class="instagram__item set-bg" data-setbg="/img/instagram/insta-6.jpg">
                        <div class="instagram__text">
                            <i class="fa fa-instagram"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Footer Section Begin -->
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6 col-sm-7">
                    <div class="footer__about">
                        <div class="footer__logo">
                            <a asp-controller="Home" asp-action="Index"><img src="~/img/logo.png" alt=""></a>
                        </div>
                        <p>
                            Explore the world of clothes and accessories
                        </p>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-5">
                    <div class="footer__widget">
                        <h6>Quick links</h6>
                        <ul>
                            <li><a asp-controller="Home" asp-action="About">About</a></li>
                            <li><a href="#">FAQ</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-lg-4 col-md-8 col-sm-8">
                    <div class="footer__newslatter">
                        <h6>NEWSLETTER</h6>
                        <form action="#">
                            <input type="text" placeholder="Email">
                            <button type="submit" class="site-btn">Subscribe</button>
                        </form>
                        <div class="footer__social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-youtube-play"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </footer>
    <!-- Footer Section End -->
    <!-- Search Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch">+</div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    @RenderSection("Scripts", required: false)
    <!-- Search End -->
    <!-- Js Plugins -->
    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/css/bootstrap.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/jquery-ui.min.js"></script>
    <script src="~/js/mixitup.min.js"></script>
    <script src="~/js/jquery.countdown.min.js"></script>
    <script src="~/js/jquery.slicknav.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.nicescroll.min.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/js/site.js"></script>


</body>

</html>